data_product_name: Gaia_Vehicle_DP
description: "This data product provides refined holiday information for the Gaia domain."
owners:
  - extern.pardeep.naik@volkswagen.de

views:
  - name: UK_holidays
    description: "Filtered public holidays for Canada only."
    columns:
      - name: countryOrRegion
        type: "VARCHAR(100)"
        description: "The name of the country or region."
      - name: date
        type: "DATE"
        description: "The calendar date of the holiday."
    definitionQuery: |
      SELECT TOP (50)
        countryOrRegion,
        date
      FROM [Gaia_Base_Tables].[dbo].[publicholidays]
      WHERE countryOrRegion = 'United Kingdom'
  - name: US_holidays
    definitionQuery: |
      SELECT TOP (20)
        countryOrRegion,
        date
      FROM [Gaia_Base_Tables].[dbo].[publicholidays]
      WHERE countryOrRegion = 'United States'